default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: countries

test:
  <<: *default
  database: countries

production:
  <<: *default
  database: countries_production
  username: countries
  password: <%= ENV['COUNTRIES_DATABASE_PASSWORD'] %>
